wg-status:
	systemctl status wg-quick@wg0
wg-restart:
	systemctl restart wg-quick@wg0
wg-start:
	systemctl start wg-quick@wg0
wg-stop:
	systemctl stop wg-quick@wg0
generate-client:
	.env > ./generate_client.sh
